import assert from 'node:assert/strict';
import { randomBytes, randomUUID } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { resolve } from 'node:path';
import { readFile } from 'node:fs/promises';
import { runner } from 'node-pg-migrate';
import { periodAt } from '../src/billing-period.js';
import { aiEntitlement,settleAi } from '../src/ai-entitlement.js';
import { after, before, test } from 'node:test';
import { Client, Pool } from 'pg';
import { createAgentApp } from '../src/app.js';
import { createOpenAIProvider } from '../src/openai.js';
import { sealBilling,type BillingContext } from '../src/billing-context.js';
import type { BillingPayment } from '../src/toss-billing.js';
import { runBillingRefundOnce } from '../src/billing-refund-execution.js';
process.loadEnvFile(resolve('../../infra/agent/.env'));
const source=process.env.AP_DATABASE_URL!, databases=new Set<string>();let admin:Client;
before(async()=>{const u=new URL(source);assert.equal(u.hostname,'127.0.0.1');assert.equal(u.port,'55431');assert.equal(u.username,'agent_local');assert.match(u.pathname,/^\/fieldai_agent_test_[a-f0-9]+$/);u.pathname='/postgres';admin=new Client({connectionString:u.toString()});await admin.connect();});
after(async()=>{try{for(const name of databases)await admin.query(`drop database "${name}" with(force)`);}finally{await admin.end();}});
async function fixture(units=1,legacy=false,anchor=new Date(Date.now()-1000),customerDailyLimit=50,paidFixture=true){
 process.env.AP_PROFILE='mock';const name='fieldai_agent_test_'+randomUUID().replaceAll('-',''),u=new URL(source);await admin.query(`create database "${name}"`);databases.add(name);u.pathname='/'+name;
 if(legacy)await runner({databaseUrl:u.toString(),dir:resolve('migrations'),direction:'up',count:79,migrationsTable:'pgmigrations',log:()=>undefined});
 const migration=legacy?{status:0,stderr:Buffer.alloc(0)}:spawnSync(process.execPath,['tools/run-migrations.mjs','agent'],{cwd:resolve('../..'),env:{...process.env,AP_DATABASE_URL:u.toString()},stdio:'pipe'});assert.equal(migration.status,0,migration.stderr.toString());
 const pool=new Pool({connectionString:u.toString()}),owner=randomUUID(),operator=randomUUID(),approver=randomUUID();
 for(const id of [owner,operator,approver])await pool.query('insert into "user"(id,name,email,"emailVerified") values($1,$2,$3,false)',[id,'Synthetic AI',id+'@example.invalid']);
 let actor=owner;let payment:BillingPayment;
 const billing:BillingContext={credentialKey:randomBytes(32),webOrigin:'http://localhost:3001',provider:{mode:'test',mid:'synthetic-mid',clientKey:'test_ck_synthetic',keyFingerprint:'a'.repeat(64),issue:async()=>'synthetic-billing',charge:async()=>{throw Error('unused');},lookup:async()=>structuredClone(payment),refund:async input=>{payment={...payment,status:'CANCELED',balanceAmount:0,suppliedAmount:0,vat:0,cancels:[{transactionKey:'synthetic-cancel-'+randomUUID(),cancelAmount:input.amount,taxFreeAmount:input.taxFreeAmount,cancelReason:input.reason,canceledAt:new Date().toISOString(),cancelStatus:'DONE',refundableAmount:0}]};return structuredClone(payment);}}};
 for(const id of [operator,approver])await pool.query("insert into ap.platform_admin_memberships(user_id,role) values($1,'operator')",[id]);
 let calls=0,mode:'valid'|'unsupported'|'timeout'|'declined'|'missing'|'known_refusal'='valid',hold:Promise<void>|undefined,release:(()=>void)|undefined,entered:(()=>void)|undefined;
 const app=createAgentApp(async()=>undefined,undefined,undefined,undefined,{pool,billing,resolveUserId:async()=>actor,resolveSession:async()=>({id:actor,userId:actor}),customerDailyLimit,testDailyLimit:3,modelProvider:{model:'synthetic-ai',async generate(input){calls++;entered?.();await hold;if(mode==='known_refusal'){const original=globalThis.fetch,key=process.env.AP_OPENAI_API_KEY,model=process.env.AP_OPENAI_MODEL;process.env.AP_OPENAI_API_KEY='synthetic-not-real';process.env.AP_OPENAI_MODEL='synthetic';globalThis.fetch=async()=>Response.json({id:'synthetic-refusal-'+randomUUID(),status:'completed',usage:{input_tokens:32,output_tokens:12},output:[{type:'message',content:[{type:'refusal',refusal:'DO-NOT-LEAK'}]}]});try{return await createOpenAIProvider()!.generate(input);}finally{globalThis.fetch=original;if(key===undefined)delete process.env.AP_OPENAI_API_KEY;else process.env.AP_OPENAI_API_KEY=key;if(model===undefined)delete process.env.AP_OPENAI_MODEL;else process.env.AP_OPENAI_MODEL=model;}}if(mode==='timeout')throw Error('synthetic timeout');if(mode==='declined')throw Error('provider_http_429');return {responseId:'synthetic-'+randomUUID(),inputTokens:32,outputTokens:12,output:{answer:'상담 서비스를 안내합니다.',evidenceIds:mode==='unsupported'?['invented']:['service:0'],unknowns:[],handoffRecommended:false},...(mode==='missing'?{inputTokens:-1}:{})};}}});
 const call=(method:'GET'|'POST'|'PUT',url:string,payload?:object)=>app.inject({method,url,payload,headers:{origin:'http://localhost:3001','idempotency-key':randomUUID()}});
 const orgResponse=await call('POST','/v1/organizations',{name:'Synthetic AI quota'});assert.equal(orgResponse.statusCode,201,orgResponse.body);const org=orgResponse.json().id;
 assert.equal((await call('PUT','/v1/knowledge/draft',{expectedRevision:0,businessName:'Synthetic',introduction:'상담 안내',services:[{name:'상담 서비스',description:'담당자 확인'}],faqs:[]})).statusCode,200);
 assert.equal((await call('POST','/v1/knowledge/releases',{expectedRevision:1})).statusCode,201);
 assert.equal((await call('PUT','/v1/agents/draft',{expectedRevision:0,name:'상담 AI',tone:'clear',guideScope:'승인 정보',handoffText:'담당자 답변'})).statusCode,200);
 assert.equal((await call('POST','/v1/agents/releases',{expectedRevision:1,expectedKnowledgeRevision:1})).statusCode,201);
 const deployment=await call('POST','/v1/deployments',{kind:'link'});assert.equal(deployment.statusCode,201,deployment.body);const publicId=deployment.json().publicId;
 assert.equal((await call('POST',`/v1/deployments/${deployment.json().id}/activate`)).statusCode,200);
 const [plan,subscription,consent,period]=[randomUUID(),randomUUID(),randomUUID(),randomUUID()];const start=anchor;
 await pool.query(`insert into ap.billing_plans(id,mode,name,total_amount,supply_amount,vat_amount,tax_free_amount,included_ai_units,grace_days,terms_version,terms_text,refund_version,refund_text,reference,requested_by,approved_by,approved_at) values($1,'test','Synthetic',11000,10000,1000,0,$2,3,'terms','Synthetic','refund','Synthetic','SYNTHETIC',$3,$4,now())`,[plan,units,operator,approver]);
 await pool.query(`insert into ap.paid_subscriptions(id,organization_id,plan_id,customer_key,state,created_by,anchor_at) values($1,$2,$3,$4,$7,$5,$6)`,[subscription,org,plan,randomUUID(),owner,paidFixture?start:null,paidFixture?'active':'awaiting_authorization']);
 await pool.query(`insert into ap.billing_consents(id,subscription_id,plan_id,accepted_by,terms_version,refund_version,total_amount,supply_amount,vat_amount,tax_free_amount,currency,included_ai_units,grace_days,auto_renew) values($1,$2,$3,$4,'terms','refund',11000,10000,1000,0,'KRW',$5,3,true)`,[consent,subscription,plan,owner,units]);
 await pool.query(`insert into ap.billing_periods(id,subscription_id,billing_period,consent_id,plan_id,starts_at,ends_at,total_amount,supply_amount,vat_amount,tax_free_amount,currency,state,paid_at) values($1,$2,0,$3,$4,$5,$6,11000,10000,1000,0,'KRW',$7,$8)`,[period,subscription,consent,plan,paidFixture?start:null,paidFixture?periodAt(start,0).endsAt:null,paidFixture?'paid':'pending',paidFixture?start:null]);
 const transaction=randomUUID();payment={paymentKey:'synthetic-payment',orderId:'ap_'+randomUUID().replaceAll('-',''),status:'DONE',totalAmount:11000,balanceAmount:11000,taxFreeAmount:0,suppliedAmount:10000,vat:1000,approvedAt:start.toISOString(),cancels:[],isPartialCancelable:true};
 if(paidFixture)await pool.query(`insert into ap.billing_transactions(id,period_id,order_id,request_key,state,mode,provider_mid,provider_key_fingerprint,payment_key_ciphertext,started_at,dispatched_at,customer_key,order_name,billing_key_ciphertext) values($1,$2,$3,$4,'succeeded','test','synthetic-mid',$5,$6,$7,$7,$8,'Synthetic',null)`,[transaction,period,payment.orderId,randomUUID(),'a'.repeat(64),sealBilling(payment.paymentKey,billing.credentialKey,`payment:${transaction}`),start,randomUUID()]);
 const refund=async()=>{actor=owner;const requested=await call('POST','/v1/subscription/refunds',{periodId:period,amount:11000,reason:'Synthetic full refund request'});assert.equal(requested.statusCode,201,requested.body);const id=requested.json().id;actor=operator;const reviewed=await call('POST',`/v1/admin/billing/refunds/${id}/review`,{reason:'Synthetic explicit review',reference:'SYNTHETIC',taxFreeAmount:0});assert.equal(reviewed.statusCode,200,reviewed.body);actor=approver;const approved=await call('POST',`/v1/admin/billing/refunds/${id}/approve`,{reason:'Synthetic different approver'});assert.equal(approved.statusCode,200,approved.body);assert.equal(await runBillingRefundOnce({pool,billing}),'succeeded');actor=owner;};
 const customer=async()=>{const r=await call('POST',`/v1/public/deployments/${publicId}/engagements`);assert.equal(r.statusCode,201,r.body);const id=r.json().id,cookie=r.headers['set-cookie']!.toString().split(';')[0];return {id,submit:()=>app.inject({method:'POST',url:`/v1/conversations/${id}/submissions`,headers:{cookie,origin:'http://localhost:3001'},payload:{name:'Synthetic customer',phone:'010-0000-1111',message:'담당자 상담 요청',consent:true}}),ask:(key=randomBytes(32).toString('base64url'))=>app.inject({method:'POST',url:`/v1/engagements/${id}/messages`,headers:{cookie,origin:'http://localhost:3001','idempotency-key':key},payload:{question:'어떤 서비스를 제공하나요?'}})};};
 return {pool,org,period,owner,subscription,customer,call,anchor,refund,apply:async()=>{await pool.query(await readFile(resolve('migrations/000080_ai_entitlement.sql'),'utf8'));},calls:()=>calls,mode:(m:typeof mode)=>{mode=m;},hold:()=>{hold=new Promise(r=>{release=r;});return new Promise<void>(r=>{entered=r;});},release:()=>{release?.();hold=undefined;entered=undefined;},close:async()=>{release?.();await app.close();await pool.end();await admin.query(`drop database "${name}"`);databases.delete(name);}};
}
test('paid customer quota reserves in flight and owner test uses a separate lane',async()=>{const f=await fixture();try{const a=await f.customer(),b=await f.customer(),entry=f.hold(),first=a.ask();await entry;const second=b.ask();await new Promise(r=>setTimeout(r,30));f.release();assert.equal((await first).statusCode,200);const denied=await second;assert.equal(denied.statusCode,429,denied.body);assert.equal(f.calls(),1);assert.equal((await f.call('POST','/v1/agents/test',{question:'어떤 서비스를 제공하나요?'})).statusCode,200);assert.equal(f.calls(),2);const summary=(await f.call('GET','/v1/usage/summary')).json();assert.equal(summary.entitlement.customer.consumedUnits,1);assert.equal(summary.entitlement.customer.remainingUnits,0);assert.equal(summary.entitlement.ownerTest.separateFromCustomer,true);}finally{await f.close();}});
test('rejected output consumes real usage once and replay does not call again',async()=>{const f=await fixture();try{f.mode('unsupported');const a=await f.customer(),key=randomBytes(32).toString('base64url');assert.equal((await a.ask(key)).statusCode,422);assert.equal((await a.ask(key)).statusCode,422);const b=await f.customer();assert.equal((await b.ask()).statusCode,429);assert.equal(f.calls(),1);}finally{await f.close();}});
test('definitive rejection releases quota while timeout holds unknown and never rePOSTs',async()=>{const f=await fixture();try{f.mode('declined');const a=await f.customer();assert.equal((await a.ask()).statusCode,503);f.mode('timeout');const b=await f.customer(),key=randomBytes(32).toString('base64url');assert.equal((await b.ask(key)).statusCode,503);const replay=await b.ask(key);assert.equal(replay.statusCode,202,replay.body);assert.equal(replay.json().state,'result_unknown');const c=await f.customer();assert.equal((await c.ask()).statusCode,429);assert.equal(f.calls(),2);assert.equal((await f.call('GET','/v1/usage/summary')).json().entitlement.customer.unknownUnits,1);}finally{await f.close();}});

test('missing provider usage holds unknown instead of returning a definite output failure',async()=>{const f=await fixture();try{f.mode('missing');const c=await f.customer(),key=randomBytes(32).toString('base64url'),r=await c.ask(key);assert.equal(r.statusCode,503,r.body);assert.equal(r.json().error,'provider_result_unknown');assert.equal((await c.ask(key)).statusCode,202);assert.equal(f.calls(),1);}finally{await f.close();}});
test('late paused output records original cost and revoked owner cannot publish a test answer',async()=>{const f=await fixture(2);try{const c=await f.customer(),entry=f.hold(),pending=c.ask();await entry;assert.equal((await c.submit()).statusCode,201);f.release();assert.equal((await pending).statusCode,409);assert.equal((await aiEntitlement(f.pool,f.org)).customer.consumedUnits,1);const entered=f.hold(),owner=f.call('POST','/v1/agents/test',{question:'어떤 서비스를 제공하나요?'});await entered;await f.pool.query("update ap.memberships set role='viewer' where organization_id=$1 and user_id=$2",[f.org,f.owner]);f.release();assert.equal((await owner).statusCode,409);assert.equal((await f.pool.query("select count(*)::int n from ap.ai_usage_ledger where lane='owner_test' and state='consumed'")).rows[0].n,1);}finally{await f.close();}});
test('grace uses the previous paid units and ended access cannot replenish credits',async()=>{const f=await fixture();try{const c=await f.customer();assert.equal((await c.ask()).statusCode,200);const end=periodAt(f.anchor,0).endsAt,grace=await aiEntitlement(f.pool,f.org,new Date(end.getTime()+1000));assert.equal(grace.access.mode,'grace');assert.equal(grace.periodId,f.period);assert.equal(grace.customer.remainingUnits,0);const expired=await aiEntitlement(f.pool,f.org,new Date(end.getTime()+4*86400000));assert.equal(expired.access.canStartNew,false);await assert.rejects(f.pool.query('update ap.billing_periods set included_ai_units=2 where id=$1',[f.period]),{code:'PAA01'});}finally{await f.close();}});
test('legacy paid known and unresolved calls bind before quota enforcement and receipts settle once',async()=>{const f=await fixture(2,true);try{const c=await f.customer(),releases=(await f.pool.query('select d.agent_release_id,a.knowledge_release_id from ap.deployments d join ap.agent_releases a on a.id=d.agent_release_id limit 1')).rows[0],known=randomUUID(),unknown=randomUUID();for(const [id,confirmed]of [[known,true],[unknown,false]] as const)await f.pool.query(`insert into ap.ai_runs(id,organization_id,agent_release_id,knowledge_release_id,kind,inquiry_id,inquiry_revision,question,status,provider_model,provider_response_id,input_tokens,output_tokens) values($1,$2,$3,$4,'customer_message',$5,0,'Legacy question',$6,'synthetic-ai',$7,$8,$9)`,[id,f.org,releases.agent_release_id,releases.knowledge_release_id,c.id,confirmed?'completed':'in_progress',confirmed?'synthetic-legacy':null,confirmed?32:null,confirmed?12:null]);await f.apply();const before=await aiEntitlement(f.pool,f.org);assert.equal(before.customer.consumedUnits,1);assert.equal(before.customer.unknownUnits,1);assert.equal(before.customer.remainingUnits,0);const receipt={responseId:'late-synthetic',inputTokens:40,outputTokens:20};await settleAi(f.pool,unknown,receipt);await settleAi(f.pool,unknown,receipt);assert.equal((await aiEntitlement(f.pool,f.org)).customer.consumedUnits,2);await assert.rejects(settleAi(f.pool,unknown,{...receipt,inputTokens:41}),/ai_receipt_conflict/);await assert.rejects(f.pool.query("update ap.ai_usage_ledger set state='released' where run_id=$1",[unknown]),{code:'PAA02'});await f.pool.query('delete from ap.ai_runs where id=$1',[known]);assert.equal((await aiEntitlement(f.pool,f.org)).customer.consumedUnits,2);}finally{await f.close();}});

test('full refund blocks new and late output while real consumption stays in the original period',async()=>{const f=await fixture(2);try{const c=await f.customer(),entry=f.hold(),pending=c.ask();await entry;await f.refund();f.release();assert.equal((await pending).statusCode,409);assert.equal(f.calls(),1);const row=(await f.pool.query('select * from ap.ai_usage_ledger')).rows[0];assert.equal(row.state,'consumed');assert.equal(row.period_id,f.period);assert.equal(row.input_tokens,32);assert.equal((await f.call('POST','/v1/agents/test',{question:'어떤 서비스를 제공하나요?'})).statusCode,403);assert.equal(f.calls(),1);assert.equal((await f.call('GET','/v1/usage/summary')).json().ai.recordedCalls,1);}finally{await f.close();}});

test('paid included units replace the trial daily limiter without changing the owner test lane',async()=>{const f=await fixture(2,false,new Date(Date.now()-1000),1);try{const a=await f.customer(),b=await f.customer();assert.equal((await a.ask()).statusCode,200);assert.equal((await b.ask()).statusCode,200);assert.equal(f.calls(),2);assert.equal((await aiEntitlement(f.pool,f.org)).customer.remainingUnits,0);}finally{await f.close();}});
test('missing usage after full refund remains unknown in its original paid period',async()=>{const f=await fixture(2);try{f.mode('missing');const c=await f.customer(),entry=f.hold(),pending=c.ask();await entry;await f.refund();f.release();const result=await pending;assert.equal(result.statusCode,503,result.body);assert.equal(result.json().error,'provider_result_unknown');const row=(await f.pool.query('select l.state,l.period_id,r.status from ap.ai_usage_ledger l join ap.ai_runs r on r.id=l.run_id')).rows[0];assert.equal(row.state,'unknown');assert.equal(row.period_id,f.period);assert.equal(row.status,'in_progress');assert.equal(f.calls(),1);}finally{await f.close();}});
test('legacy grace call stays on previous units when renewal payment was approved after the call',async()=>{const anchor=new Date();anchor.setUTCMonth(anchor.getUTCMonth()-1);anchor.setTime(anchor.getTime()-1500);const f=await fixture(2,true,anchor);try{const c=await f.customer(),releases=(await f.pool.query('select d.agent_release_id,a.knowledge_release_id from ap.deployments d join ap.agent_releases a on a.id=d.agent_release_id limit 1')).rows[0],run=randomUUID(),next=randomUUID(),started=new Date(Date.now()-500);await f.pool.query(`insert into ap.ai_runs(id,organization_id,agent_release_id,knowledge_release_id,kind,inquiry_id,inquiry_revision,question,status,provider_model,provider_response_id,input_tokens,output_tokens,started_at) values($1,$2,$3,$4,'customer_message',$5,0,'Grace call','completed','synthetic-ai','grace-synthetic',10,5,$6)`,[run,f.org,releases.agent_release_id,releases.knowledge_release_id,c.id,started]);const period=periodAt(anchor,1);await f.pool.query(`insert into ap.billing_periods(id,subscription_id,billing_period,consent_id,plan_id,starts_at,ends_at,total_amount,supply_amount,vat_amount,tax_free_amount,currency,state,paid_at) select $1,subscription_id,1,consent_id,plan_id,$2,$3,total_amount,supply_amount,vat_amount,tax_free_amount,currency,'paid',clock_timestamp() from ap.billing_periods where id=$4`,[next,period.startsAt,period.endsAt,f.period]);await f.apply();assert.equal((await f.pool.query('select period_id from ap.ai_usage_ledger where run_id=$1',[run])).rows[0].period_id,f.period);}finally{await f.close();}});
test('answer publication holds the same organization lock as a concurrent refund',async()=>{const f=await fixture(2);let unblock=()=>{};const original=f.pool.connect;try{let signal=()=>{},armed=true;const read=new Promise<void>(r=>{signal=r;}),pause=new Promise<void>(r=>{unblock=r;});Object.defineProperty(f.pool,'connect',{configurable:true,value:(...args:unknown[])=>{const result=Reflect.apply(original,f.pool,args);if(args.length)return result;return result.then((client:import('pg').PoolClient)=>{const query=client.query;Object.defineProperty(client,'query',{configurable:true,value:async(...input:unknown[])=>{const answer=await Reflect.apply(query,client,input);if(armed&&f.calls()===1&&typeof input[0]==='string'&&input[0].includes('from ap.billing_periods p left join ap.ai_usage_ledger')){armed=false;signal();await pause;}return answer;}});return client;});}});const c=await f.customer(),entry=f.hold(),pending=c.ask();await entry;f.release();await read;let completed=false;const refund=f.refund().then(()=>{completed=true;});await new Promise(r=>setTimeout(r,100));const serialized=!completed;unblock();assert.equal((await pending).statusCode,200);await refund;assert.equal(serialized,true,'refund must wait until answer publication commits');}finally{unblock();Object.defineProperty(f.pool,'connect',{configurable:true,value:original});await f.close();}});

test('mock customer lane preserves its existing rolling daily budget',async()=>{const f=await fixture(2,false,new Date(Date.now()-1000),1,false);try{const a=await f.customer(),b=await f.customer();assert.equal((await a.ask()).statusCode,200);assert.equal((await b.ask()).statusCode,429);assert.equal(f.calls(),1);const usage=await aiEntitlement(f.pool,f.org);assert.equal(usage.access.mode,'mock_unconfigured');assert.equal(usage.periodId,null);assert.equal(usage.customer.includedUnits,null);}finally{await f.close();}});

test('real adapter refusal with confirmed usage consumes a paid unit without exposing or publishing output',async()=>{const f=await fixture();try{f.mode('known_refusal');const c=await f.customer(),r=await c.ask();assert.equal(r.statusCode,422,r.body);assert.equal(r.json().error,'provider_output_rejected');assert.doesNotMatch(r.body,/DO-NOT-LEAK/);const row=(await f.pool.query('select state,input_tokens,output_tokens from ap.ai_usage_ledger')).rows[0];assert.equal(row.state,'consumed');assert.equal(row.input_tokens,32);assert.equal(row.output_tokens,12);const b=await f.customer();assert.equal((await b.ask()).statusCode,429);assert.equal(f.calls(),1);}finally{await f.close();}});
