import React from "react";
import { ScreenContent, type Screen } from "@fieldai/ui";

function ChatFrame({customer}:{customer:boolean}) { return <div className="chat-preview"><div className="chat-preview-head">{customer ? "사업자 AI 상담" : "응대 테스트"} · 활성화 전</div><div className="chat-preview-empty"><strong>아직 답변할 정보가 없습니다</strong><p>사업자가 지식을 승인하고 AI를 활성화하면 이곳에서 실제 응대를 확인합니다.</p></div><div className="chat-preview-compose"><input aria-label="질문" placeholder="질문을 입력해 주세요"/><button type="button" disabled>보내기</button></div></div>; }

export function AgentPreviewContent({screen}:{screen:Screen}) {
  if (screen.id === "AP-O02") return <div className="special-grid"><section className="special-panel"><div className="panel-heading"><h2>직접 입력 · 초안</h2><span>미저장</span></div><p>사업자가 확인한 사실만 입력합니다. 승인 전 고객 응대에 반영되지 않습니다.</p><div className="form-fields"><label>상호<input placeholder="실제 상호" /></label><label>지역<input placeholder="운영 지역" /></label><label>서비스<input placeholder="제공 서비스" /></label><label>운영시간<input placeholder="실제 운영시간" /></label></div><label className="preview-textarea-label">사업 소개<textarea placeholder="직접 확인한 소개를 입력해 주세요" /></label><label className="preview-textarea-label">자주 묻는 질문<textarea placeholder="질문과 확인된 답변을 입력해 주세요" /></label><div className="preview-action"><button type="button" disabled>초안 저장</button><button type="button" disabled>승인 버전 만들기</button><p>권한·지식 API 연결 전에는 입력 내용을 저장하거나 승인할 수 없습니다.</p></div></section><aside className="special-panel"><h2>출처와 승인 상태</h2><div className="customer-banner"><strong>승인된 지식 없음</strong><p>고객 AI는 승인된 정보만 근거로 사용합니다. 가격·경력·후기는 임의로 만들지 않습니다.</p></div><div className="knowledge-source"><strong>직접 입력</strong><span>저장 전</span><p>AP에서 작성한 사업 정보와 FAQ</p></div><div className="knowledge-source"><strong>외부 정보 검토</strong><span>미연결</span><p>외부 앱의 승인 정보는 출처·버전·변경 내역을 검토한 뒤 별도로 반영합니다.</p></div></aside></div>;
  if (screen.id === "AP-O04") return <div className="inbox-layout"><section className="inbox-list"><div className="panel-heading"><h2>상담 목록</h2><span>AP 원본</span></div><div className="inbox-filters"><span>전체</span><span>사람 응대 필요</span><span>답변 대기</span></div><div className="empty-state"><span className="empty-mark" aria-hidden="true">○</span><h3>아직 상담이 없습니다</h3><p>AP 링크 또는 위젯에서 시작한 상담이 여기에 표시됩니다.</p></div></section><section className="inbox-detail"><h2>대화 상세</h2><div className="empty-state"><h3>상담을 선택해 주세요</h3><p>원문, 고객 공개 답변, 내부 메모와 AI/사람 응대 상태를 구분합니다.</p></div></section></div>;
  if (screen.id === "AP-O05") return <div className="special-grid"><section className="special-panel"><h2>상담 배포 방법</h2><p>기본 상담 배포에는 홍보 카드와 제휴 매체가 필요하지 않습니다.</p><div className="deployment-options"><div><strong>상담 링크</strong><p>AP 고객 화면으로 바로 연결</p><span>미발급</span></div><div><strong>사이트 위젯</strong><p>소유한 기존 사이트에 설치</p><span>주소 미검증</span></div></div><div className="preview-action"><button type="button" disabled>배포 만들기</button><p>도메인 검증과 권한 API 연결 후 사용할 수 있습니다.</p></div></section><aside className="special-panel"><h2>설치 확인 순서</h2><div className="approval-steps"><div className="approval-step"><span>01</span><div>사이트 주소 확인<small>정확한 origin만 허용</small></div></div><div className="approval-step"><span>02</span><div>설치 코드 발급<small>공개 배포 ID만 브라우저에 포함</small></div></div><div className="approval-step"><span>03</span><div>고객 화면 테스트<small>실제 대화와 안전 접수 확인</small></div></div></div></aside></div>;
  if (screen.id === "AP-O06") return <div className="special-grid"><section className="special-panel"><h2>연동 앱</h2><p>연결 앱마다 조직, actor, 정보 출처와 허용 scope를 따로 확인합니다.</p><div className="customer-banner"><strong>연결된 앱이 없습니다</strong><p>AP는 외부 앱이 없어도 사업 AI와 상담을 운영할 수 있습니다.</p></div><div className="preview-action"><button type="button" disabled>앱 연결</button><p>양방향 동의 화면이 구현되면 이용할 수 있습니다.</p></div></section><aside className="special-panel"><h2>연결 후 확인할 항목</h2><div className="approval-steps"><div className="approval-step"><span>01</span><div>상대 제품과 조직<small>AP 로그인으로 상대 제품에 로그인하지 않음</small></div></div><div className="approval-step"><span>02</span><div>공유 정보와 권한<small>scope와 갱신 상태 표시</small></div></div><div className="approval-step"><span>03</span><div>연결 해제<small>구독 해지·원본 삭제와 구분</small></div></div></div></aside></div>;
  if (screen.id === "AP-O03") return <div className="special-grid"><section className="special-panel"><h2>AI 설정</h2><p>응대 방식은 승인된 사업 정보와 함께 관리됩니다.</p><div className="form-fields"><label>AI 이름<input placeholder="사업 AI 이름"/></label><label>인사말<input placeholder="고객에게 보여줄 첫 문장"/></label><label>응대 말투<input placeholder="말투를 설명해 주세요"/></label><label>사람에게 넘길 조건<input placeholder="확인할 수 없는 질문 등"/></label></div><div className="preview-action"><button type="button" disabled>설정 저장</button><p>권한과 승인 API 연결 후 사용할 수 있습니다.</p></div></section><aside className="special-panel"><h2>고객에게 보여줄 응대</h2><p>테스트 실행은 실제 AI 연결 후 가능합니다.</p><ChatFrame customer={false}/></aside></div>;
  if (screen.id === "AP-C01") return <div className="special-grid"><section className="special-panel"><h2>사업자 AI 상담</h2><p>사업자와 AI 이용 안내를 확인한 뒤 질문을 남깁니다.</p><ChatFrame customer={true}/></section><aside className="special-panel"><h2>문의 방법</h2><div className="customer-banner"><strong>AI 상담은 아직 활성화되지 않았습니다</strong><p>현재 화면은 디자인 검토본입니다. 고객 질문을 저장하거나 AI 답변을 생성하지 않습니다.</p></div><div className="preview-action"><button type="button" disabled>사람에게 문의</button><p>안전 접수 화면의 API 연결 후 이용할 수 있습니다.</p></div></aside></div>;
  if (screen.id === "AP-C02") return <div className="special-grid"><section className="special-panel"><div className="panel-heading"><h2>안전한 문의 접수</h2><span>제출 전</span></div><p>연락처와 사진은 AP의 1차 상담 화면에서만 제출합니다.</p><div className="form-fields"><label>이름<input autoComplete="name" placeholder="성함" /></label><label>연락처<input type="tel" autoComplete="tel" placeholder="연락받을 번호" /></label></div><label className="preview-textarea-label">문의 내용<textarea placeholder="문의 내용을 입력해 주세요" /></label><div className="knowledge-source"><strong>사진 첨부</strong><span>미연결</span><p>파일 저장·검사 API 연결 후 첨부할 수 있습니다. 사진을 자동 진단하지 않습니다.</p><button type="button" disabled>사진 첨부</button></div><div className="preview-action"><button type="button" disabled>문의 제출</button><p>접수 API 연결 전에는 입력 내용이 저장되지 않습니다.</p></div></section><aside className="special-panel"><h2>접수 후 접근</h2><div className="customer-banner"><strong>미인증 번호</strong><p>이름과 번호로 접수할 수 있지만 번호의 소유가 확인된 상태로 표시하지 않습니다.</p></div><div className="knowledge-source"><strong>현재 브라우저</strong><p>실제 접수 후 대화 범위의 안전한 세션으로 이어갑니다.</p></div><div className="knowledge-source"><strong>별도 접수 확인키</strong><p>새 브라우저에서 원문을 보려면 알림 링크와 분리된 확인키를 사용합니다. 번호나 알림 링크만으로 원문을 열지 않습니다.</p></div></aside></div>;
  return <ScreenContent screen={screen}/>;
}
