'use client';
import React,{useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import { currentBillingIdentity } from './billing-client';
import { loadBillingAdmin,adminBillingActionReason,adminBillingNotice,prepareAdminBillingMutation,listAdminBillingMutations,submitAdminBillingMutation,type AdminBillingSnapshot,type AdminBillingAction,type AdminBillingAttempt } from './billing-admin-client';
const labels:Record<string,string>={pending:'처리 대기',processing:'결과 확인 중',unknown:'결과 확인 필요',succeeded:'완료',failed:'실패',canceled:'취소',blocked_integration:'연동 설정 필요',requested:'검토 대기',reviewed:'다른 승인 대기',rejected:'거절',approved:'승인',retired:'판매 중지'};
const amount=(v:number)=>`${v.toLocaleString('ko-KR')}원`;
const time=(v:string)=>new Date(v).toLocaleString('ko-KR');
const badge=(state:string)=><span className={`billing-admin-badge ${['succeeded','approved'].includes(state)?'green':['requested','reviewed','pending'].includes(state)?'blue':['failed','rejected'].includes(state)?'red':['unknown','processing','blocked_integration'].includes(state)?'amber':'gray'}`}>{labels[state]??state}</span>;
type Body=Record<string,string|number>;
type ViewProps={snapshot:AdminBillingSnapshot;busy:boolean;notice:string;onRefresh:()=>void;onAction:(action:AdminBillingAction,id:string|null,body:Body)=>void;attempts?:AdminBillingAttempt[]};
function ActionForm({action,id,snapshot,busy,onAction,attempt}:Pick<ViewProps,'snapshot'|'busy'|'onAction'>&{action:AdminBillingAction;id:string;attempt?:AdminBillingAttempt}){
 const reason=adminBillingActionReason(snapshot,action,id),name=action==='plan-approve'?'다른 운영자 승인':action==='plan-retire'?'판매 중지':action==='refund-review'?'검토 기록':action==='refund-approve'?'다른 운영자 실행 승인':'요청 거절';
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);onAction(action,id,{reason:String(fd.get('reason')??''),...(action==='refund-review'?{reference:String(fd.get('reference')??''),taxFreeAmount:Number(fd.get('taxFreeAmount'))}:{})});}
 return <form className="billing-admin-action-form" onSubmit={submit}><h4>{name}</h4><fieldset disabled={busy||Boolean(reason)||Boolean(attempt)}><label>사유<textarea name="reason" minLength={10} maxLength={500} required defaultValue={String(attempt?.body.reason??'')} /></label>
 {action==='refund-review'&&<><label>거래·정책 검토 근거<input name="reference" maxLength={160} required defaultValue={String(attempt?.body.reference??'')} /></label><label>환불 면세 금액 (원)<input name="taxFreeAmount" type="number" min="0" max="1000000000" step="1" required defaultValue={attempt?.body.taxFreeAmount??''} /></label></>}
 <button type="submit">{name}</button></fieldset>{reason&&<p className="billing-admin-note">{reason}</p>}{attempt&&<p className="billing-admin-note">원래 요청을 확인 중입니다. 아래 동일 요청 재시도를 사용해 주세요.</p>}</form>;
}
export function BillingAdminView({snapshot,busy,notice,onRefresh,onAction,attempts=[]}:ViewProps){const s=snapshot,find=(a:AdminBillingAction,id:string|null)=>attempts.find(v=>v.action===a&&v.targetId===id);
 const rows=[...s.overview.transactions.map(t=>({id:`charge-${t.id}`,org:t.organizationName,event:t.billingPeriod===0?'첫 구독 결제':t.state==='failed'?'갱신 결제 실패':'월 구독 갱신',amount:t.amount,state:t.state,createdAt:t.createdAt,mode:t.mode,refundId:null})),
 ...s.refunds.map(r=>({id:`refund-${r.id}`,org:r.organizationId,event:'구독 환불 요청',amount:r.amount,state:r.state,createdAt:r.createdAt,mode:s.overview.refundExecution.find(x=>x.id===r.id)?.mode??'미확인',refundId:r.id}))].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,100);
 function planSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget),body:Body={};for(const name of ['mode','name','termsVersion','termsText','refundVersion','refundText','reference'])body[name]=String(fd.get(name)??'');for(const name of ['totalAmount','supplyAmount','vatAmount','taxFreeAmount','includedAiUnits','graceDays'])body[name]=Number(fd.get(name));onAction('plan-request',null,body);}
 const planAttempt=find('plan-request',null);
 return <section className="billing-admin" aria-label="구독·청구"><p className="billing-admin-description">사업자의 플랫폼 구독만 관리합니다. 고객 서비스 대금은 포함하지 않습니다.</p>
 <div className="billing-admin-summary-grid">{[['확인할 결제',s.overview.counts.unconfirmedCharges],['갱신 실패',s.overview.counts.renewalFailures],['환불 요청',s.overview.counts.refundRequests]].map(([label,count])=><div className="billing-admin-card billing-admin-stat-card" key={label}><div className="billing-admin-stat-label">{label}</div><div className="billing-admin-stat-value">{count}<span>건</span></div></div>)}</div>
 <div className="billing-admin-card billing-admin-list-card"><div className="billing-admin-table-tools"><h2>최근 구독 이벤트</h2><button type="button" disabled={busy} onClick={onRefresh}>결과 조회</button></div>
 {rows.length===0?<p className="billing-admin-empty">표시할 구독 이벤트가 없습니다.</p>:<table className="billing-admin-table"><thead><tr>{['사업체','이벤트','금액','상태','처리'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td data-label="사업체"><strong>{r.org}</strong></td><td data-label="이벤트">{r.event}<p>{r.mode==='test'?'테스트':r.mode==='live'?'실적':'환경 미확인'} · {time(r.createdAt)}</p></td><td data-label="금액">{amount(r.amount)}</td><td data-label="상태">{badge(r.state)}</td><td data-label="처리">{r.refundId?<a href={`#refund-${r.refundId}`}>요청 검토</a>:<button type="button" disabled={busy} onClick={onRefresh}>내역 확인</button>}</td></tr>)}</tbody></table>}</div>
 <div className="billing-admin-notice">결제 결과가 불확실하면 PG 상태 조회를 먼저 수행합니다. 타임아웃을 실패로 간주해 중복 청구하지 않습니다.<p>이 화면은 원장을 다시 조회합니다. 공급사 결과 대조는 기존 서버 worker가 같은 거래로 수행합니다.</p></div>
 {notice&&<p role="status" className="billing-admin-notice">{notice}</p>}
 {attempts.length>0&&<section className="billing-admin-card billing-admin-added"><h2>동일 요청 복구 (추가)</h2>{attempts.map(a=><article key={`${a.action}:${a.targetId}`}><p>{a.action} · {a.targetId??'새 가격'} · {a.stage==='unknown'?'결과 확인 필요':'전송 준비'}</p><p>멱등 요청 {a.requestKey}</p><button type="button" disabled={busy||s.overview.role!=='operator'} onClick={()=>onAction(a.action,a.targetId,a.body)}>동일 요청 재시도</button><p className="billing-admin-note">다른 내용이나 새 UUID로 실행하지 않습니다.</p></article>)}</section>}
 <section className="billing-admin-card billing-admin-added"><h2>가격 승인 관리 (추가)</h2><p>가격 버전은 승인 뒤 변경할 수 없습니다. 판매 중지는 신규 판매만 제한하고 기존 구독 조건을 유지합니다.</p>
 <details><summary>가격 승인 요청 (추가)</summary><form className="billing-admin-form" onSubmit={planSubmit}><fieldset disabled={busy||s.overview.role!=='operator'||Boolean(planAttempt)}>
 <label>환경<select name="mode" defaultValue={planAttempt?.body.mode??'test'}><option value="test">테스트</option><option value="live">실판매 승인 요청</option></select></label><label>플랜 이름<input name="name" required maxLength={100} defaultValue={String(planAttempt?.body.name??'')} /></label>
 <div className="billing-admin-form-grid">{[['totalAmount','총 금액 (원)',1,1e9],['supplyAmount','공급가액 (원)',0,1e9],['vatAmount','부가세 (원)',0,1e9],['taxFreeAmount','면세 금액 (원)',0,1e9],['includedAiUnits','AI 제공량',1,1e7],['graceDays','실패 유예 (일)',0,30]].map(([name,label,min,max])=><label key={name}>{label}<input name={String(name)} type="number" min={min} max={max} step="1" required defaultValue={planAttempt?.body[String(name)]??''} /></label>)}</div>
 {['terms','refund'].map(v=><React.Fragment key={v}><label>{v==='terms'?'약관':'환불 조건'} 버전<input name={`${v}Version`} required maxLength={100} defaultValue={String(planAttempt?.body[`${v}Version`]??'')} /></label><label>{v==='terms'?'약관':'환불 조건'} 전문<textarea name={`${v}Text`} required minLength={10} maxLength={8000} defaultValue={String(planAttempt?.body[`${v}Text`]??'')} /></label></React.Fragment>)}
 <label>운영비·가격 승인 근거<input name="reference" required maxLength={160} defaultValue={String(planAttempt?.body.reference??'')} /></label><button type="submit">가격 승인 요청</button></fieldset></form></details>
 {s.plans.length===0?<p>가격 버전이 없습니다.</p>:s.plans.map(p=><article key={p.id}><h3>{p.name} {badge(p.state)}</h3><p>{p.mode==='test'?'테스트':'실판매'} · {amount(p.totalAmount)} / 월 · 공급가 {amount(p.supplyAmount)} · VAT {amount(p.vatAmount)} · 면세 {p.taxFreeAmount===null?'미확인':amount(p.taxFreeAmount)}</p><p>AI 제공량 {p.includedAiUnits.toLocaleString('ko-KR')} · 유예 {p.graceDays}일</p><p>요청 운영자 {p.requestedBy} · 승인 운영자 {p.approvedBy??'대기'}</p><p>근거 {p.reference}</p><details><summary>가격·조건 검토 (추가)</summary><h4>약관 {p.termsVersion}</h4><p className="billing-admin-policy">{p.termsText}</p><h4>환불 조건 {p.refundVersion}</h4><p className="billing-admin-policy">{p.refundText}</p>
 {(['plan-approve','plan-retire'] as const).map(a=><ActionForm key={a} action={a} id={p.id} snapshot={s} busy={busy} onAction={onAction} attempt={find(a,p.id)} />)}</details></article>)}</section>
 <section className="billing-admin-card billing-admin-added"><h2>환불 검토·승인 (추가)</h2><p>구독 환불 요청을 검토한 뒤 다른 운영자가 실행을 승인합니다. 환불은 구독 갱신 중지나 고객 서비스 대금 환불이 아닙니다.</p>
 {s.refunds.length===0?<p>환불 요청이 없습니다.</p>:s.refunds.map(r=><article id={`refund-${r.id}`} key={r.id}><h3>구독 환불 {badge(r.state)}</h3><p>조직 {r.organizationId} · 기간 {r.periodId}</p><p>{amount(r.amount)} · 면세 {r.taxFreeAmount===null?'검토 전':amount(r.taxFreeAmount)} · 환불 정책 {r.refundVersion}</p><p>고객 요청 사유: {r.reason}</p><p>요청 {r.requestedBy} · 검토 {r.reviewedBy??'대기'} · 승인 {r.approvedBy??'대기'}</p>{r.reference&&<p>근거 {r.reference}</p>}{r.reviewReason&&<p>검토 사유 {r.reviewReason}</p>}{r.approvalReason&&<p>승인 사유 {r.approvalReason}</p>}<p>{time(r.createdAt)}{r.completedAt?` · 완료 ${time(r.completedAt)}`:''}</p>
 {['pending','processing','unknown','blocked_integration'].includes(r.state)&&<p className="billing-admin-note">실행 결과는 원장과 같은 거래 대조로 확인합니다. 새 환불이나 재청구를 만들지 않습니다.{r.errorCode?` (${r.errorCode})`:''}</p>}
 <details><summary>요청 검토·다른 승인 (추가)</summary>{(['refund-review','refund-approve','refund-reject'] as const).map(a=><ActionForm key={a} action={a} id={r.id} snapshot={s} busy={busy} onAction={onAction} attempt={find(a,r.id)} />)}</details></article>)}</section>
 <p className="billing-admin-note">{s.overview.role==='auditor'?'조회 전용':'운영자'} · 조회 {time(s.overview.snapshotAt)} · 최근 목록은 각 100건입니다.</p></section>;
}
function pending(s:AdminBillingSnapshot){return listAdminBillingMutations(s.context,window.sessionStorage);}
export function BillingAdmin(){const [snapshot,setSnapshot]=useState<AdminBillingSnapshot|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[attempts,setAttempts]=useState<AdminBillingAttempt[]>([]);const epoch=useRef(0),mounted=useRef(true);
 const load=useCallback(async()=>{const ticket=++epoch.current;setBusy(true);setSnapshot(null);setAttempts([]);try{const value=await loadBillingAdmin(window.location.origin);if(!mounted.current||ticket!==epoch.current)return;const restored=pending(value);setSnapshot(value);setAttempts(restored);setNotice('');return value;}catch(e){if(mounted.current&&ticket===epoch.current)setNotice(adminBillingNotice(e));}finally{if(mounted.current&&ticket===epoch.current)setBusy(false);}},[]);
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;epoch.current++;};},[load]);
 async function mutate(action:AdminBillingAction,id:string|null,body:Body){if(!snapshot||busy)return;const current=snapshot,ticket=++epoch.current;setBusy(true);setNotice('');try{const identity=await currentBillingIdentity();if(identity.userId!==current.context.userId||identity.sessionId!==current.context.sessionId){if(mounted.current&&ticket===epoch.current){setSnapshot(null);setAttempts([]);setNotice('로그인이 변경됐습니다. 현재 제품에서 다시 조회해 주세요.');}return;}
 const a=prepareAdminBillingMutation(action,id,body,current.context,window.sessionStorage);await submitAdminBillingMutation(a,current.context,window.sessionStorage);const after=await currentBillingIdentity();if(!mounted.current||ticket!==epoch.current)return;if(after.userId!==current.context.userId||after.sessionId!==current.context.sessionId){setSnapshot(null);setAttempts([]);setNotice('로그인이 변경됐습니다. 현재 제품에서 다시 조회해 주세요.');return;}const refreshed=await load();if(mounted.current&&refreshed?.context.userId===current.context.userId&&refreshed.context.sessionId===current.context.sessionId)setNotice(action==='refund-approve'?'환불 실행 승인을 접수했습니다. worker 결과는 원장으로 확인해 주세요.':'요청을 원장에 기록했습니다.');
 }catch(e){if(mounted.current&&ticket===epoch.current){setNotice(adminBillingNotice(e));try{setAttempts(pending(current));}catch{setNotice('원래 요청 정보를 확인하지 못했습니다. 새 요청을 만들지 말고 원장을 조회해 주세요.');}}}finally{if(mounted.current&&ticket===epoch.current)setBusy(false);}}
 if(!snapshot)return <section className="billing-admin"><p role="status">{busy?'현재 제품의 관리자 권한과 구독 원장을 확인 중입니다.':notice}</p><button type="button" disabled={busy} onClick={()=>void load()}>구독 원장 다시 조회</button></section>;
 return <BillingAdminView key={`${snapshot.context.userId}:${snapshot.context.sessionId}`} snapshot={snapshot} busy={busy} notice={notice} attempts={attempts} onRefresh={()=>void load()} onAction={(a,id,body)=>void mutate(a,id,body)} />;
}
