import { billingProduct, currentBillingIdentity, parseBillingPlan, type BillingPlan, type BillingIdentity } from './billing-client';
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const object=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const text=(v:unknown,max:number,min=1):v is string=>typeof v==='string'&&v.trim().length>=min&&v.length<=max&&!/[\u0000-\u001f]/.test(v);
// 환불 사유는 API가 줄바꿈 등 문자 제한 없이 trim 후 저장하므로 같은 기준(길이만)으로 받는다.
const storedText=(v:unknown,max:number):v is string=>typeof v==='string'&&v.trim().length>=1&&v.length<=max;
const date=(v:unknown):v is string=>typeof v==='string'&&Number.isFinite(Date.parse(v));
const nullableDate=(v:unknown)=>v===null||date(v);
const integer=(v:unknown,min:number,max:number)=>Number.isSafeInteger(v)&&Number(v)>=min&&Number(v)<=max;
function safeText(v:unknown,max:number,min=1,policy=false):v is string{return typeof v==='string'&&v.trim().length>=min&&v.length<=max&&!(policy?/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/:/[\u0000-\u001f]/).test(v)&&!/(?:authKey|billingKey|paymentKey|secretKey|clientKey|customerKey|sk_(?:live|test)|toss\.[A-Za-z0-9_-]+)\s*[:=_-]?/i.test(v)&&!/(?:\d[ -]?){13,19}/.test(v);}
const originValid=(value:string)=>{try{const u=new URL(value);return u.origin===value&&!u.username&&!u.password&&(u.protocol==='https:'||u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname));}catch{return false;}};
export type AdminBillingContext=BillingIdentity&{origin:string};
export type AdminPlan=BillingPlan&{reference:string;requestedBy:string;approvedBy:string|null;approvedAt:string|null;createdAt:string};
export type AdminRefund={id:string;organizationId:string;periodId:string;amount:number;taxFreeAmount:number|null;state:string;reason:string;refundVersion:string;
 createdAt:string;reviewedAt:string|null;approvedAt:string|null;completedAt:string|null;errorCode:string|null;requestedRole:string;requestedBy:string;reviewedBy:string|null;approvedBy:string|null;reference:string|null;reviewReason:string|null;approvalReason:string|null};
export type AdminCharge={id:string;organizationId:string;organizationName:string;periodId:string;billingPeriod:number;amount:number;state:string;mode:string;createdAt:string;completedAt:string|null;errorCode:string|null};
export type AdminBillingOverview={product:typeof billingProduct;actorUserId:string;sessionId:string;role:'operator'|'auditor';snapshotAt:string;
 counts:{unconfirmedCharges:string;renewalFailures:string;refundRequests:string};transactions:AdminCharge[];refundExecution:{id:string;mode:'test'|'live';dispatchedAt:string|null}[]};
export type AdminBillingSnapshot={context:AdminBillingContext;overview:AdminBillingOverview;plans:AdminPlan[];refunds:AdminRefund[]};
export type AdminBillingAction='plan-request'|'plan-approve'|'plan-retire'|'refund-review'|'refund-approve'|'refund-reject';
type StoragePort=Pick<Storage,'getItem'|'setItem'|'removeItem'>;
export type AdminBillingAttempt={version:1;product:typeof billingProduct;action:AdminBillingAction;targetId:string|null;context:AdminBillingContext;body:Record<string,string|number>;requestKey:string;stage:'prepared'|'unknown'};
export class AdminBillingError extends Error{constructor(readonly code:string,readonly status=0){super(code);}}
const error=(code='billing_admin_result_unknown',status=0)=>new AdminBillingError(code,status);
function parsePlan(v:unknown):AdminPlan|null{const b=object(v),p=parseBillingPlan(v);if(!p||!text(b.reference,160)||!text(b.requestedBy,200)||b.approvedBy!==null&&!text(b.approvedBy,200)||!nullableDate(b.approvedAt)||!date(b.createdAt))return null;
 return {...p,reference:b.reference,requestedBy:b.requestedBy,approvedBy:b.approvedBy as string|null,approvedAt:b.approvedAt as string|null,createdAt:b.createdAt};}
function parseRefund(v:unknown):AdminRefund|null{const b=object(v);if(!uuid.test(String(b.id))||!uuid.test(String(b.organizationId))||!uuid.test(String(b.periodId))||!integer(b.amount,1,1e9)||b.taxFreeAmount!==null&&!integer(b.taxFreeAmount,0,Number(b.amount))
 ||!['requested','reviewed','pending','processing','unknown','succeeded','rejected','blocked_integration'].includes(String(b.state))||!storedText(b.reason,500)||!text(b.refundVersion,100)||!date(b.createdAt)||['reviewedAt','approvedAt','completedAt'].some(k=>!nullableDate(b[k]))
 ||!['owner','operator'].includes(String(b.requestedRole))||!text(b.requestedBy,200)||['reviewedBy','approvedBy','reference','reviewReason','approvalReason','errorCode'].some(k=>b[k]!==null&&!(k.endsWith('Reason')?storedText(b[k],500):text(b[k],k==='reference'?160:200))))return null;
 return {id:b.id as string,organizationId:b.organizationId as string,periodId:b.periodId as string,amount:b.amount as number,taxFreeAmount:b.taxFreeAmount as number|null,state:b.state as string,reason:b.reason,refundVersion:b.refundVersion,
 createdAt:b.createdAt,reviewedAt:b.reviewedAt as string|null,approvedAt:b.approvedAt as string|null,completedAt:b.completedAt as string|null,errorCode:b.errorCode as string|null,requestedRole:b.requestedRole as string,requestedBy:b.requestedBy,reviewedBy:b.reviewedBy as string|null,approvedBy:b.approvedBy as string|null,reference:b.reference as string|null,reviewReason:b.reviewReason as string|null,approvalReason:b.approvalReason as string|null};}
function parseOverview(v:unknown):AdminBillingOverview{const b=object(v),c=object(b.counts);if(b.product!==billingProduct||!text(b.actorUserId,200)||!text(b.sessionId,200)||!['operator','auditor'].includes(String(b.role))||!date(b.snapshotAt)
 ||['unconfirmedCharges','renewalFailures','refundRequests'].some(k=>typeof c[k]!=='string'||!/^\d{1,15}$/.test(c[k] as string))||!Array.isArray(b.transactions)||b.transactions.length>100||!Array.isArray(b.refundExecution)||b.refundExecution.length>100)throw error();
 const transactions=b.transactions.map((v:unknown)=>{const t=object(v);if(!uuid.test(String(t.id))||!uuid.test(String(t.organizationId))||!uuid.test(String(t.periodId))||!text(t.organizationName,200)||!integer(t.billingPeriod,0,1e6)||!integer(t.amount,1,1e9)||!['pending','processing','unknown','succeeded','failed','canceled','blocked_integration'].includes(String(t.state))||!['test','live'].includes(String(t.mode))||!date(t.createdAt)||!nullableDate(t.completedAt)||t.errorCode!==null&&!text(t.errorCode,200))throw error();
 return {id:t.id as string,organizationId:t.organizationId as string,organizationName:t.organizationName,periodId:t.periodId as string,billingPeriod:t.billingPeriod as number,amount:t.amount as number,state:t.state as string,mode:t.mode as string,createdAt:t.createdAt,completedAt:t.completedAt as string|null,errorCode:t.errorCode as string|null};});
 const refundExecution=b.refundExecution.map((v:unknown)=>{const r=object(v);if(!uuid.test(String(r.id))||!['test','live'].includes(String(r.mode))||!nullableDate(r.dispatchedAt))throw error();return{id:r.id as string,mode:r.mode as 'test'|'live',dispatchedAt:r.dispatchedAt as string|null};});
 return {product:billingProduct,actorUserId:b.actorUserId,sessionId:b.sessionId,role:b.role as 'operator'|'auditor',snapshotAt:b.snapshotAt,counts:{unconfirmedCharges:c.unconfirmedCharges as string,renewalFailures:c.renewalFailures as string,refundRequests:c.refundRequests as string},transactions,refundExecution};}
async function request(path:string,init:RequestInit,fetcher:typeof fetch){let response:Response;try{response=await fetcher(path,{...init,credentials:'same-origin',cache:'no-store'});}catch{throw error();}let b:unknown;try{b=await response.json();}catch{throw error('billing_admin_result_unknown',response.status);}
 if(!response.ok){const code=object(b).error;throw error(typeof code==='string'&&/^[a-z0-9_]{1,100}$/.test(code)?code:'billing_admin_request_refused',response.status);}return b;}
const sameContext=(a:AdminBillingContext,b:AdminBillingContext)=>a.userId===b.userId&&a.sessionId===b.sessionId&&a.origin===b.origin;
function validContext(c:AdminBillingContext){if(!text(c.userId,200)||!text(c.sessionId,200)||!originValid(c.origin))throw error('billing_admin_binding_invalid');}
export async function loadBillingAdmin(origin:string,fetcher:typeof fetch=fetch):Promise<AdminBillingSnapshot>{const identity=await currentBillingIdentity(fetcher),context={...identity,origin};validContext(context);
 const [ov,pv,rv]=await Promise.all([request('/v1/admin/billing/overview',{},fetcher),request('/v1/admin/billing/plans',{},fetcher),request('/v1/admin/billing/refunds',{},fetcher)]),overview=parseOverview(ov),p=object(pv),r=object(rv);
 if(overview.actorUserId!==identity.userId||overview.sessionId!==identity.sessionId||!sameContext({...await currentBillingIdentity(fetcher),origin},context))throw error('billing_admin_binding_invalid');
 if(p.product!==billingProduct||r.product!==billingProduct||!Array.isArray(p.plans)||p.plans.length>100||!Array.isArray(r.refunds)||r.refunds.length>100)throw error();
 const plans=p.plans.map(parsePlan),refunds=r.refunds.map(parseRefund);if(plans.some(v=>!v)||refunds.some(v=>!v))throw error();return {context,overview,plans:plans as AdminPlan[],refunds:refunds as AdminRefund[]};}
export function adminBillingActionReason(s:AdminBillingSnapshot,action:AdminBillingAction,id:string|null):string|null{
 if(s.overview.role!=='operator')return '조회 전용 운영자입니다.';if(action==='plan-request')return null;
 if(action.startsWith('plan-')){const p=s.plans.find(v=>v.id===id);if(!p)return '가격 버전을 다시 조회해 주세요.';if(action==='plan-approve'){
 if(p.state!=='pending')return '승인 대기 가격만 승인할 수 있습니다.';if(p.requestedBy===s.context.userId)return '가격 요청과 다른 운영자가 승인해야 합니다.';if(p.mode==='live')return '실판매 가격 승인 설정이 연결되지 않았습니다.';}else if(p.state==='retired')return '이미 판매 중지된 가격입니다.';return null;}
 const r=s.refunds.find(v=>v.id===id),execution=s.overview.refundExecution.find(v=>v.id===id);if(!r||!execution)return '환불 요청과 실행 상태를 다시 조회해 주세요.';
 if(action==='refund-review'&&r.state!=='requested')return '검토 대기 환불만 검토할 수 있습니다.';
 if(action==='refund-approve'){if(r.state!=='reviewed')return '운영자 검토 후 다른 운영자가 승인합니다.';if(r.reviewedBy===s.context.userId||r.requestedRole==='operator'&&r.requestedBy===s.context.userId)return '검토자·대행 요청자와 다른 운영자가 승인해야 합니다.';if(execution.mode==='live')return '실환불 공급사와 추가 인증이 연결되지 않았습니다.';}
 if(action==='refund-reject'&&(execution.dispatchedAt!==null||!['requested','reviewed','pending','blocked_integration'].includes(r.state)))return '전송되거나 결과 미상인 환불은 거절할 수 없습니다.';return null;}
function normalizedBody(action:AdminBillingAction,raw:unknown):Record<string,string|number>{const b=object(raw);let allowed:string[],result:Record<string,string|number>;
 if(action==='plan-request'){allowed=['mode','name','totalAmount','supplyAmount','vatAmount','taxFreeAmount','includedAiUnits','graceDays','termsVersion','termsText','refundVersion','refundText','reference'];
 if(!['test','live'].includes(String(b.mode))||!safeText(b.name,100)||!safeText(b.reference,160)||!safeText(b.termsVersion,100)||!safeText(b.refundVersion,100)||!safeText(b.termsText,8000,10,true)||!safeText(b.refundText,8000,10,true)
 ||!integer(b.totalAmount,1,1e9)||!integer(b.supplyAmount,0,1e9)||!integer(b.vatAmount,0,1e9)||!integer(b.taxFreeAmount,0,Number(b.totalAmount))||Number(b.totalAmount)!==Number(b.supplyAmount)+Number(b.vatAmount)||Number(b.vatAmount)!==Math.round((Number(b.totalAmount)-Number(b.taxFreeAmount))/11)||!integer(b.includedAiUnits,1,1e7)||!integer(b.graceDays,0,30))throw error('billing_admin_input_invalid');
 result={mode:String(b.mode),name:String(b.name).trim(),totalAmount:Number(b.totalAmount),supplyAmount:Number(b.supplyAmount),vatAmount:Number(b.vatAmount),taxFreeAmount:Number(b.taxFreeAmount),includedAiUnits:Number(b.includedAiUnits),graceDays:Number(b.graceDays),termsVersion:String(b.termsVersion).trim(),termsText:String(b.termsText).trim(),refundVersion:String(b.refundVersion).trim(),refundText:String(b.refundText).trim(),reference:String(b.reference).trim()};
 }else{allowed=action==='refund-review'?['reason','reference','taxFreeAmount']:['reason'];if(!safeText(b.reason,500,10))throw error('billing_admin_input_invalid');result={reason:String(b.reason).trim()};if(action==='refund-review'){if(!safeText(b.reference,160)||!integer(b.taxFreeAmount,0,1e9))throw error('billing_admin_input_invalid');result={...result,reference:String(b.reference).trim(),taxFreeAmount:Number(b.taxFreeAmount)};}}
 if(Object.keys(b).some(k=>!allowed.includes(k)))throw error('billing_admin_input_invalid');return result;}
const actions:AdminBillingAction[]=['plan-request','plan-approve','plan-retire','refund-review','refund-approve','refund-reject'];
export function adminBillingStorageKey(action:AdminBillingAction,id:string|null,c:AdminBillingContext){return `${billingProduct}:billing-admin:v1:${encodeURIComponent(JSON.stringify([c.userId,c.sessionId,c.origin,action,id]))}`;}
function readAttempt(raw:string|null):AdminBillingAttempt|null{try{if(!raw||raw.length>20000)return null;const a=object(JSON.parse(raw)),c=object(a.context);if(a.version!==1||a.product!==billingProduct||!actions.includes(a.action as AdminBillingAction)||!uuid.test(String(a.requestKey))||!['prepared','unknown'].includes(String(a.stage))||a.targetId!==null&&!uuid.test(String(a.targetId))||Object.keys(a).some(k=>!['version','product','action','targetId','context','body','requestKey','stage'].includes(k))||Object.keys(c).some(k=>!['userId','sessionId','origin'].includes(k)))return null;
 const context={userId:c.userId as string,sessionId:c.sessionId as string,origin:c.origin as string};validContext(context);const action=a.action as AdminBillingAction;if(action==='plan-request'?a.targetId!==null:a.targetId===null)return null;return{version:1,product:billingProduct,action,targetId:a.targetId as string|null,context,body:normalizedBody(action,a.body),requestKey:a.requestKey as string,stage:a.stage as 'prepared'|'unknown'};}catch{return null;}}
function readStored(action:AdminBillingAction,id:string|null,c:AdminBillingContext,store:StoragePort){let raw:string|null;try{raw=store.getItem(adminBillingStorageKey(action,id,c));}catch{throw error('billing_admin_storage_unavailable');}if(raw===null)return null;const a=readAttempt(raw);if(!a||a.action!==action||a.targetId!==id||!sameContext(a.context,c))throw error('billing_admin_metadata_invalid');return a;}
function persist(a:AdminBillingAttempt,store:StoragePort){const key=adminBillingStorageKey(a.action,a.targetId,a.context),raw=JSON.stringify(a);try{store.setItem(key,raw);if(store.getItem(key)!==raw)throw error();}catch{throw error('billing_admin_storage_unavailable');}}
export function restoreAdminBillingMutation(action:AdminBillingAction,id:string|null,c:AdminBillingContext,store:StoragePort){validContext(c);return readStored(action,id,c,store);}
export function listAdminBillingMutations(c:AdminBillingContext,store:StoragePort&Pick<Storage,'length'|'key'>):AdminBillingAttempt[]{validContext(c);const prefix=`${billingProduct}:billing-admin:v1:`,result:AdminBillingAttempt[]=[];
 try{const length=store.length;for(let i=0;i<length;i++){const key=store.key(i);if(!key?.startsWith(prefix))continue;let tuple:unknown;try{tuple=JSON.parse(decodeURIComponent(key.slice(prefix.length)));}catch{continue;}
  if(!Array.isArray(tuple)||tuple.length!==5||tuple[0]!==c.userId||tuple[1]!==c.sessionId||tuple[2]!==c.origin)continue;
  const action=tuple[3],id=tuple[4];if(!actions.includes(action)||id!==null&&!uuid.test(String(id)))throw error('billing_admin_metadata_invalid');
  const a=readStored(action,id,c,store);if(!a)throw error('billing_admin_metadata_invalid');result.push(a);
 }return result;}catch(e){if(e instanceof AdminBillingError)throw e;throw error('billing_admin_storage_unavailable');}}
export function prepareAdminBillingMutation(action:AdminBillingAction,id:string|null,body:unknown,c:AdminBillingContext,store:StoragePort,createKey=()=>crypto.randomUUID()):AdminBillingAttempt{validContext(c);if(!actions.includes(action)||(action==='plan-request'?id!==null:!uuid.test(String(id))))throw error('billing_admin_input_invalid');const normalized=normalizedBody(action,body),old=readStored(action,id,c,store);
 if(old){if(JSON.stringify(old.body)!==JSON.stringify(normalized))throw error('idempotency_conflict',409);return old;}const requestKey=createKey();if(!uuid.test(requestKey))throw error('billing_admin_input_invalid');const a:AdminBillingAttempt={version:1,product:billingProduct,action,targetId:id,context:{...c},body:normalized,requestKey,stage:'prepared'};persist(a,store);return a;}
const locks=new WeakMap<object,Set<string>>();
export async function submitAdminBillingMutation(a:AdminBillingAttempt,c:AdminBillingContext,store:StoragePort,fetcher:typeof fetch=fetch):Promise<{id:string;state:string}>{validContext(c);if(a.product!==billingProduct||!sameContext(a.context,c))throw error('billing_admin_binding_invalid');const saved=readStored(a.action,a.targetId,c,store);if(!saved||saved.requestKey!==a.requestKey||JSON.stringify(saved.body)!==JSON.stringify(a.body))throw error('billing_admin_metadata_invalid');
 const storageKey=adminBillingStorageKey(a.action,a.targetId,c);let active=locks.get(store);if(!active){active=new Set();locks.set(store,active);}if(active.has(storageKey))throw error('billing_admin_in_progress');active.add(storageKey);
 const clear=()=>{const old=readStored(a.action,a.targetId,c,store);if(!old||old.requestKey!==a.requestKey||JSON.stringify(old.body)!==JSON.stringify(a.body))throw error('billing_admin_metadata_invalid');try{store.removeItem(storageKey);if(store.getItem(storageKey)!==null)throw error();}catch{throw error('billing_admin_storage_unavailable');}};
 try{const identity=await currentBillingIdentity(fetcher),overview=parseOverview(await request('/v1/admin/billing/overview',{},fetcher));if(!sameContext({...identity,origin:c.origin},c)||overview.actorUserId!==c.userId||overview.sessionId!==c.sessionId)throw error('billing_admin_binding_invalid');if(overview.role!=='operator')throw error('operator_membership_required',403);
 persist({...saved,stage:'unknown'},store);const [kind,action]=a.action.split('-'),path=a.action==='plan-request'?'/v1/admin/billing/plans':`/v1/admin/billing/${kind==='plan'?'plans':'refunds'}/${a.targetId}/${action}`;
 let v:unknown;try{v=await request(path,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':a.requestKey,'X-Admin-Billing-Actor-Id':c.userId,'X-Admin-Billing-Session-Id':c.sessionId},body:JSON.stringify(a.body)},fetcher);}catch(e){const precommit=e instanceof AdminBillingError&&(['invalid_billing_plan','invalid_billing_plan_action','invalid_refund_action'].includes(e.code)&&e.status===400||e.code==='different_approver_required'&&e.status===403);
 if(saved.stage==='prepared'&&precommit)clear();throw e;}
 let receipt:{id:string;state:string};if(a.action==='plan-request'){const b=object(v);if(!uuid.test(String(b.id)))throw error();receipt={id:b.id as string,state:'pending'};}
 else if(kind==='plan'){const p=parsePlan(v),expected=action==='approve'?'approved':'retired';if(!p||p.id!==a.targetId||p.state!==expected)throw error();receipt={id:p.id,state:p.state};}
 else{const r=parseRefund(v),expected=action==='review'?'reviewed':action==='approve'?'pending':'rejected';if(!r||r.id!==a.targetId||r.state!==expected)throw error();receipt={id:r.id,state:r.state};}clear();return receipt;
 }finally{active.delete(storageKey);}}
export function adminBillingNotice(e:unknown){const code=e instanceof AdminBillingError?e.code:object(e).code;return ({authentication_required:'현재 제품에 로그인해 주세요.',current_session_required:'현재 제품에 다시 로그인해 주세요.',admin_membership_required:'현재 제품 관리자 권한이 필요합니다.',operator_membership_required:'현재 운영자 권한이 없어 변경하지 않았습니다.',blocked_integration:'추가 인증 또는 공급사 설정이 연결되지 않았습니다.',live_price_approval_not_configured:'실판매 가격 승인 설정이 연결되지 않았습니다.',different_approver_required:'요청자·검토자와 다른 운영자가 승인해야 합니다.',billing_admin_binding_invalid:'원래 제품 계정·로그인 창에서 동일 요청을 확인해 주세요.',billing_admin_input_invalid:'명시된 정수 금액·조건·사유를 확인하고 카드·인증 비밀값은 입력하지 마세요.',billing_admin_storage_unavailable:'재시도 정보를 저장하지 못했습니다. 원래 요청의 상태를 확인해 주세요.',billing_admin_metadata_invalid:'원래 요청 정보를 확인하지 못했습니다. 새 UUID로 덮어쓰지 말고 내역을 확인해 주세요.',billing_admin_in_progress:'같은 요청을 처리 중입니다.',idempotency_conflict:'원래 요청과 내용이 다릅니다. 동일 내용으로 원래 요청을 확인해 주세요.'} as Record<string,string>)[String(code)]??'결과를 확인하지 못했습니다. 동일 요청으로 재시도하거나 원장 상태를 다시 조회해 주세요.';}
