import React from "react";
import { ScreenContent, type Screen } from "@fieldai/ui";
import { FieldEditorPreview } from "./editor-preview";
import { FieldBookingPreview } from "./booking-preview";

function DisabledAction({label}:{label:string}) { return <div className="preview-action"><button type="button" disabled>{label}</button><p>실제 저장·승인 API 연결 후 사용할 수 있습니다.</p></div>; }

function SiteFrame({title}:{title:string}) { return <div className="site-preview" aria-label="사이트 화면 구조"><div className="site-preview-bar"><strong>내 사이트</strong><span>미공개</span></div><div className="site-preview-body"><h3>{title}</h3><p>사업자가 승인한 소개와 서비스가 이곳에 표시됩니다.</p><span className="site-preview-cta">문의 남기기</span></div></div>; }

export function FieldPreviewContent({screen}:{screen:Screen}) {
  if (screen.id === "F-O08") return <><div className="dashboard-stats">{[["새 직접 문의","—"],["예약 확인 대기","—"],["알림 실패","—"]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong><small>실제 데이터 연결 전</small></div>)}</div><div className="special-grid"><section className="special-panel"><h2>오늘 처리할 일</h2><div className="empty-state"><span className="empty-mark" aria-hidden="true">○</span><h3>아직 표시할 업무가 없습니다</h3><p>직접 문의와 예약 요청이 연결되면 출처와 상태를 함께 표시합니다.</p></div></section><aside className="special-panel"><h2>연동 상태</h2><div className="customer-banner"><strong>AI 상담 미연결</strong><p>Field의 직접 문의와 예약은 AP 연결 여부와 관계없이 계속 이용합니다.</p></div></aside></div></>;
  if (screen.id === "F-O09") return <div className="inbox-layout"><section className="inbox-list"><div className="panel-heading"><h2>문의</h2><span>출처별 목록</span></div><div className="inbox-filters"><span>전체</span><span>Field 직접 문의</span><span>외부 AI 상담</span></div><div className="empty-state"><span className="empty-mark" aria-hidden="true">○</span><h3>표시할 문의가 없습니다</h3><p>연결된 실제 문의가 있으면 출처와 답변 상태를 이곳에 표시합니다.</p></div></section><section className="inbox-detail"><h2>대화 상세</h2><div className="empty-state"><h3>문의를 선택해 주세요</h3><p>Field 원본은 여기서 답변하고 외부 AI 원본은 권한을 확인해 AP API에서 읽습니다.</p></div></section></div>;
  if (screen.id === "F-O10") return <div className="special-grid"><section className="special-panel"><h2>예약·달력</h2><p>요청과 확정, 수동 일정을 같은 자원 기준으로 확인합니다.</p><div className="calendar-grid">{["일","월","화","수","목","금","토"].map(day=><strong key={day}>{day}</strong>)}{Array.from({length:28},(_,index)=><span key={index}>{index+1}</span>)}</div><div className="preview-action"><button type="button" disabled>수동 일정 추가</button><p>실제 예약 DB 연결 후 사용할 수 있습니다.</p></div></section><aside className="special-panel"><h2>예약 요청</h2><div className="empty-state"><h3>대기 중인 요청이 없습니다</h3><p>요청 수락 시 점유 충돌을 다시 검사합니다. 요청 저장만으로 확정되지 않습니다.</p></div></aside></div>;
  if (screen.id === "F-O13") return <div className="special-grid"><section className="special-panel"><h2>AI 상담 연결</h2><p>Agent Platform은 별도 계정과 요금을 사용하는 외부 서비스입니다.</p><div className="customer-banner"><strong>현재 미연결</strong><p>사이트 제작·직접 문의·예약은 계속 사용할 수 있습니다.</p></div><div className="approval-steps"><div className="approval-step"><span>01</span><div>양쪽 계정 확인<small>Field와 AP의 조직·사용자 동의를 각각 확인</small></div></div><div className="approval-step"><span>02</span><div>정보·권한 선택<small>사업 소개, 서비스, 문의·예약 권한을 별도 승인</small></div></div><div className="approval-step"><span>03</span><div>사이트에 설치<small>AP 공식 SDK와 검증된 사이트 주소 사용</small></div></div></div><div className="preview-action"><button type="button" disabled>기존 계정 연결</button><p>공식 연결 계약 구현 후 이용할 수 있습니다.</p></div></section><aside className="special-panel"><h2>별도 제품 안내</h2><p>AI 상담을 원하면 AP 제품을 확인할 수 있습니다. Field 계정으로 자동 로그인되지 않습니다.</p><p><a className="related-link" href={process.env.NEXT_PUBLIC_AGENT_WEB_URL ?? "http://localhost:3001"}>Agent Platform 보기 ↗</a></p></aside></div>;
  if (screen.id === "F-O03") return <section className="special-panel"><h2>사이트 배치 선택</h2><p>입력한 사업 정보가 각 배치에 적용됩니다. 아래 그림은 내용이 없는 화면 구조입니다.</p><div className="template-grid">{[
    {name:"Essential",body:"한 페이지에서 서비스와 문의를 빠르게 확인",style:"essential"},
    {name:"Editorial",body:"이미지와 이야기를 넓게 보여주는 구성",style:"editorial"},
    {name:"Warm",body:"소개와 연락 경로를 친근하게 배치",style:"warm"}
  ].map((item,index)=><label className="template-card" key={item.name}><div className={`template-sample ${item.style}`} aria-hidden="true"><i/><i/><i/><i/></div><input type="radio" name="template" defaultChecked={index===0}/><strong>{item.name}</strong><small>{item.body}</small></label>)}</div><DisabledAction label="디자인 선택"/></section>;
  if (screen.id === "F-O05") return <div className="special-grid"><section className="special-panel"><div className="panel-heading"><h2>직접 문의·연락</h2><span>설정 전</span></div><p>고객은 AP 없이 사이트에서 직접 문의하거나 사업자에게 전화할 수 있습니다.</p><div className="form-fields"><label>문의 안내<input placeholder="문의 전에 보여줄 안내" /></label><label>전화번호<input type="tel" placeholder="공개할 사업자 번호" /></label><label>운영시간<input placeholder="실제 운영시간" /></label></div><fieldset className="booking-modes"><legend>기본 예약 방식 미리보기</legend><label><input type="radio" name="owner-booking-mode" defaultChecked />희망시간 제출형</label><label><input type="radio" name="owner-booking-mode" />시간표 선택형</label></fieldset><p className="setting-hint">서비스마다 다른 방식을 선택할 수 있습니다. 요청은 사업자 승인 전까지 확정되지 않습니다.</p><DisabledAction label="설정 저장"/></section><aside className="special-panel"><h2>연락 경로 확인</h2><div className="knowledge-source"><strong>직접 문의</strong><p>비회원 문의가 Field 원본으로 접수됩니다. 실제 저장 전에는 접수 완료로 표시하지 않습니다.</p></div><div className="knowledge-source"><strong>예약</strong><p>희망시간 또는 시간표 선택 후 사업자가 최종 확인합니다.</p></div><div className="customer-banner"><strong>AP 연결은 선택</strong><p>AI 상담을 연결하지 않아도 직접 문의·예약과 사이트 공개를 설정할 수 있습니다.</p></div></aside></div>;
  if (screen.id === "F-O04") return <FieldEditorPreview/>;
  if (screen.id === "F-C01") return <div className="special-grid"><section className="special-panel"><h2>고객에게 보이는 사이트</h2><p>승인된 사업 정보가 공개되면 이 영역에 표시됩니다.</p><SiteFrame title="사업 정보 공개 전"/></section><aside className="special-panel"><h2>현재 공개 상태</h2><div className="customer-banner"><strong>사이트가 아직 공개되지 않았습니다</strong><p>실제 사업자 사이트가 공개되기 전에는 임의의 서비스·가격·사진을 표시하지 않습니다.</p></div><DisabledAction label="직접 문의"/></aside></div>;
  if (screen.id === "F-C04") return <div className="special-grid"><section className="special-panel"><div className="panel-heading"><h2>비회원 문의</h2><span>제출 전</span></div><p>AI 서비스 가입 없이 사업자에게 직접 남기는 문의입니다.</p><div className="form-fields"><label>이름<input autoComplete="name" placeholder="성함" /></label><label>연락처<input type="tel" autoComplete="tel" placeholder="연락받을 번호" /></label></div><label className="preview-textarea-label">문의 내용<textarea placeholder="문의 내용을 입력해 주세요" /></label><div className="knowledge-source"><strong>사진 첨부</strong><span>미연결</span><p>실제 파일 저장·검사 API가 연결되면 첨부할 수 있습니다.</p><button type="button" disabled>사진 첨부</button></div><div className="preview-action"><button type="button" disabled>문의 제출</button><p>Field 접수 API 연결 전에는 입력 내용이 저장되지 않습니다.</p></div></section><aside className="special-panel"><h2>접수 후 대화</h2><div className="customer-banner"><strong>번호만으로 원문 접근 불가</strong><p>연락처는 미인증이며 접수 대화의 열람 권한이 되지 않습니다.</p></div><div className="knowledge-source"><strong>현재 브라우저</strong><p>실제 접수 후 안전한 세션으로 대화를 이어갑니다.</p></div><div className="knowledge-source"><strong>별도 확인키</strong><p>새 브라우저에서는 알림 링크와 분리된 확인키로 접근을 확인합니다.</p></div></aside></div>;
  if (screen.id === "F-C05") return <FieldBookingPreview/>;
  return <ScreenContent screen={screen}/>;
}
